apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appsprofile
  name: appsprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsprofile
  strategy: 
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 1
       maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appsprofile
    spec:
      containers:
      - image: shonphand/springboot-apps
        name: appsprofile
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi            
        livenessProbe:
         successThreshold: 2
         failureThreshold: 2
         initialDelaySeconds: 5
         periodSeconds: 5
         httpGet:
           path: /customers/100
           port: 8080
        readinessProbe:
         successThreshold: 2
         failureThreshold: 2
         initialDelaySeconds: 5
         periodSeconds: 5
         httpGet:
           path: /customers/100
           port: 8080