apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: appsprofile
  name: appsprofile
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30081
  selector:
    app: appsprofile
  type: NodePort
status:
  loadBalancer: {}