apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appscurrency
  name: appscurrency
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appscurrency
  strategy: 
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 1
       maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appscurrency
    spec:
      containers:
      - image: shonphand/golang_app2
        name: appscurrency
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi            
        livenessProbe:
         successThreshold: 2
         failureThreshold: 2
         initialDelaySeconds: 5
         periodSeconds: 5
         httpGet:
           path: /currency/BTCUSD
           port: 8080
        readinessProbe:
         successThreshold: 2
         failureThreshold: 2
         initialDelaySeconds: 25
         periodSeconds: 5
         httpGet:
           path: /currency/BTCUSD
           port: 8080
